services:

  postgres:
    image: postgres:17
    container_name: order-inventory-postgres

    environment:
      POSTGRES_DB: order_inventory
      POSTGRES_USER: order_user
      POSTGRES_PASSWORD: order_password

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: